// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-Zx2o9T11sZBSqx-RSFuQrceiFCMUfI',
    appId: '1:337021706296:web:bcb486e86d04c2326046cd',
    messagingSenderId: '337021706296',
    projectId: 'pin-drop-chat-e2ee',
    authDomain: 'pin-drop-chat-e2ee.firebaseapp.com',
    storageBucket: 'pin-drop-chat-e2ee.firebasestorage.app',
    measurementId: 'G-NVEDW5F4DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfLV2bZc3LjTgi-en2JF6yrKxTFOnOdU',
    appId: '1:337021706296:android:1a0bf90218337d0b6046cd',
    messagingSenderId: '337021706296',
    projectId: 'pin-drop-chat-e2ee',
    storageBucket: 'pin-drop-chat-e2ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1FiS82AGlBvFZUGkJD4PLsfok8o_NLgA',
    appId: '1:337021706296:ios:09633e224e35e8156046cd',
    messagingSenderId: '337021706296',
    projectId: 'pin-drop-chat-e2ee',
    storageBucket: 'pin-drop-chat-e2ee.firebasestorage.app',
    iosBundleId: 'com.example.pinDropChat',
  );
}
